# Generated by Django 4.0.6 on 2022-07-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('log_name', models.CharField(blank=True, max_length=191, null=True)),
                ('description', models.TextField()),
                ('subject_type', models.CharField(blank=True, max_length=191, null=True)),
                ('subject_id', models.CharField(blank=True, max_length=36, null=True)),
                ('causer_type', models.CharField(blank=True, max_length=191, null=True)),
                ('causer_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswersHistory',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApprovedLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'approved_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlockingReasons',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('is_block', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('temporary', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blocking_reasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAi',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('front_document', models.TextField()),
                ('back_document', models.TextField()),
                ('first_photo', models.TextField()),
                ('second_photo', models.TextField()),
                ('third_photo', models.TextField()),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('id_onboarding', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_ai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=191)),
                ('identifier', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientFiles',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientFilesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_files_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientHistoryLocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_date', models.DateTimeField(blank=True, null=True)),
                ('unlocked_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_history_locks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('dui', models.CharField(max_length=191, unique=True)),
                ('nit', models.CharField(max_length=191)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=191)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=191)),
                ('alternative_number_phone', models.CharField(blank=True, max_length=191, null=True)),
                ('promotional_code', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_level_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLevelLoanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('requested_at', models.DateTimeField()),
                ('overdue_installments_count', models.IntegerField()),
            ],
            options={
                'db_table': 'client_level_loan_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientLoanScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=36)),
                ('loan_id', models.CharField(max_length=36)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_approved', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_loan_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientNumberPhoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_number_phone', models.CharField(max_length=191)),
                ('next_number_phone', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_number_phone_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('number_phone', models.CharField(max_length=191, unique=True)),
                ('invitation_code', models.CharField(max_length=191)),
                ('level_at', models.DateField()),
                ('loans_requested', models.IntegerField()),
                ('verified', models.IntegerField()),
                ('notify', models.IntegerField()),
                ('special', models.IntegerField()),
                ('status', models.CharField(max_length=191)),
                ('block_at', models.DateField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_verified', models.IntegerField()),
                ('bo_verified', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientScoreEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=36)),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_type', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('term_type', models.CharField(blank=True, max_length=255, null=True)),
                ('term_status', models.CharField(blank=True, max_length=255, null=True)),
                ('balance_status', models.CharField(blank=True, max_length=255, null=True)),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('due_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('due_days', models.IntegerField(blank=True, null=True)),
                ('category_1', models.CharField(blank=True, max_length=255, null=True)),
                ('category_2', models.CharField(blank=True, max_length=255, null=True)),
                ('collateral', models.CharField(blank=True, max_length=255, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('grant_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client_score_entities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientScores',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=36)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('risk', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.CharField(blank=True, max_length=300, null=True)),
                ('scored_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientSpecialDataBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'client_special_data_base_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientTokenVerifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=191)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'client_token_verifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAnalytics',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('default_probability', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_analytics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('iso_code', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('client_id', models.CharField(max_length=36)),
                ('client_type', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FailedJobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('connection', models.TextField()),
                ('queue', models.TextField()),
                ('payload', models.TextField()),
                ('exception', models.TextField()),
                ('failed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'failed_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=191)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FileCategories',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'file_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransactions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField(blank=True, null=True)),
                ('commission_amount', models.IntegerField()),
                ('commission_tax', models.IntegerField()),
                ('interest_amount', models.IntegerField()),
                ('interest_tax', models.IntegerField()),
                ('overdue_amount', models.IntegerField()),
                ('overdue_tax', models.IntegerField()),
                ('invoiced_at', models.DateField()),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransactionTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice_transaction_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'invoice_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('queue', models.CharField(max_length=191)),
                ('payload', models.TextField()),
                ('attempts', models.PositiveIntegerField()),
                ('reserved_at', models.PositiveIntegerField(blank=True, null=True)),
                ('available_at', models.PositiveIntegerField()),
                ('created_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelAmounts',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('available', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'level_amounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LevelPeriod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'level_period',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
                ('order', models.IntegerField()),
                ('commission', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_loans', models.IntegerField()),
                ('min_time', models.IntegerField()),
                ('normal', models.IntegerField()),
                ('special', models.IntegerField()),
                ('active', models.IntegerField()),
                ('require_minimum_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanApprovalReasons',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_approval_reasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('number_fee', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('principal_amount', models.BigIntegerField(blank=True, null=True)),
                ('interest_amount', models.BigIntegerField(blank=True, null=True)),
                ('iva_interest_amount', models.BigIntegerField(blank=True, null=True)),
                ('due', models.BigIntegerField()),
                ('debt_paid', models.BigIntegerField(blank=True, null=True)),
                ('paid', models.BigIntegerField()),
                ('status', models.IntegerField()),
                ('expire_at', models.DateField()),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanDetailUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_detail_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanDueRemovals',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('due', models.FloatField()),
                ('installment_number', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_due_removals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanPenalties',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('description', models.CharField(max_length=191)),
                ('days_in_arrears', models.IntegerField()),
                ('days_to_block', models.IntegerField()),
                ('block_client', models.IntegerField()),
                ('is_temporary_block', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_penalties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanReferrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_referrals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRejectionReasons',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('is_active', models.IntegerField()),
                ('block', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_rejection_reasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanRepayments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('installment_number', models.IntegerField()),
                ('principal_amount', models.BigIntegerField()),
                ('interest_amount', models.BigIntegerField()),
                ('interest_tax_amount', models.BigIntegerField()),
                ('overdue_amount', models.BigIntegerField()),
                ('overdue_tax_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('balance_available', models.BigIntegerField()),
                ('refund_amount', models.BigIntegerField()),
                ('repayment_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_repayments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanReversals',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loan_reversals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=191, null=True)),
                ('correlative', models.CharField(blank=True, max_length=191, null=True)),
                ('amount', models.BigIntegerField()),
                ('commission', models.BigIntegerField(blank=True, null=True)),
                ('installment_amount', models.BigIntegerField(blank=True, null=True)),
                ('interest', models.BigIntegerField(blank=True, null=True)),
                ('iva_interest', models.BigIntegerField(blank=True, null=True)),
                ('period_name', models.CharField(blank=True, max_length=191, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('repeat', models.IntegerField(blank=True, null=True)),
                ('year_rate', models.FloatField(blank=True, null=True)),
                ('iva_rate', models.FloatField(blank=True, null=True)),
                ('applied_percentage', models.BigIntegerField()),
                ('due_rate', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.IntegerField()),
                ('is_blocked', models.IntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('score_granted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanTigoMoneyDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'loan_tigo_money_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Migrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migration', models.CharField(max_length=191)),
                ('batch', models.IntegerField()),
            ],
            options={
                'db_table': 'migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipalities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('nit_code', models.CharField(max_length=191, unique=True)),
                ('postal_code', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipalities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField()),
                ('type', models.IntegerField()),
                ('params', models.CharField(blank=True, max_length=10, null=True)),
                ('sms', models.IntegerField()),
                ('push', models.IntegerField()),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=191)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=191)),
                ('token', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'password_resets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_n', models.CharField(blank=True, max_length=191, null=True)),
                ('company_code', models.CharField(blank=True, max_length=191, null=True)),
                ('reference', models.CharField(blank=True, max_length=191, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.CharField(blank=True, max_length=191, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=191, null=True)),
                ('msisdn', models.CharField(blank=True, max_length=191, null=True)),
                ('process_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=191)),
                ('expected_amount', models.BigIntegerField(blank=True, null=True)),
                ('advance_amount', models.BigIntegerField(blank=True, null=True)),
                ('processed_due', models.BigIntegerField(blank=True, null=True)),
                ('expected_due', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('days', models.CharField(blank=True, max_length=191, null=True)),
                ('repeat', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodSettings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('min_days', models.IntegerField()),
                ('max_days', models.IntegerField(blank=True, null=True)),
                ('fee', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('value', models.IntegerField()),
                ('days_to_add', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'period_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('guard_name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=191)),
                ('for_field', models.CharField(blank=True, db_column='for', max_length=191, null=True)),
                ('required', models.IntegerField()),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('mode', models.CharField(max_length=8)),
                ('validation_endpoint', models.CharField(blank=True, max_length=191, null=True)),
                ('order', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuotePayments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('due', models.BigIntegerField()),
                ('residue', models.BigIntegerField()),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quote_payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referrals',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('percentage_to_apply', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'referrals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RejectedLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rejected_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepaymentPartTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
                ('order', models.IntegerField(unique=True)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repayment_part_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReversalTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=191)),
                ('name', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'reversal_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('guard_name', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreCategories',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('from_days', models.IntegerField()),
                ('to_days', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('year_rate', models.FloatField()),
                ('due_rate', models.FloatField()),
                ('iva_rate', models.FloatField()),
                ('referral_percentage', models.IntegerField()),
                ('referring_percentage', models.IntegerField()),
                ('maximum_referral_percentage', models.IntegerField()),
                ('period_grace', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialDataBaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_code', models.CharField(blank=True, max_length=191, null=True)),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('last_name', models.CharField(blank=True, max_length=191, null=True)),
                ('email', models.CharField(blank=True, max_length=191, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=191, null=True)),
                ('dui', models.CharField(blank=True, db_column='DUI', max_length=191, null=True)),
                ('nit', models.CharField(blank=True, db_column='NIT', max_length=191, null=True)),
                ('registered', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_data_base_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialDataBases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191, unique=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('characteristics', models.CharField(blank=True, max_length=191, null=True)),
                ('active', models.IntegerField()),
                ('automatic', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(max_length=12)),
                ('pattern', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'special_data_bases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
                ('order', models.PositiveIntegerField(unique=True)),
                ('is_active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'steps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubTicketTypeFields',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('source', models.JSONField(blank=True, null=True)),
                ('source_origin', models.CharField(blank=True, max_length=8, null=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('default_value_origin', models.CharField(blank=True, max_length=9, null=True)),
                ('others', models.IntegerField()),
                ('required', models.IntegerField()),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('mask', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_ticket_type_fields',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubTicketTypeOptions',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField()),
                ('type', models.CharField(max_length=5)),
                ('active', models.IntegerField()),
                ('compare_values', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_ticket_type_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubTicketTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('active', models.IntegerField()),
                ('notify', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_ticket_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubTicketTypeValues',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('resolved', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sub_ticket_type_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemNotifications',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=191)),
                ('notifiable_type', models.CharField(max_length=191)),
                ('notifiable_id', models.PositiveBigIntegerField()),
                ('data', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketFollowers',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_followers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketLoanInstallments',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pending_installment_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_loan_installments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketReminderTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'ticket_reminder_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketResultTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
            ],
            options={
                'db_table': 'ticket_result_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=191, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=191, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('total_pending_amount', models.BigIntegerField(blank=True, null=True)),
                ('promised_payment_amount', models.BigIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1500, null=True)),
                ('promise_status', models.CharField(blank=True, max_length=9, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatuses',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('order', models.IntegerField()),
                ('code', models.CharField(max_length=191, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_statuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketTypes',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191)),
                ('code', models.CharField(max_length=191)),
                ('management', models.IntegerField()),
            ],
            options={
                'db_table': 'ticket_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TigoMoney',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('n_account', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('min_amount', models.BigIntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tigo_money',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TigoMoneyDetails',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('incoming', models.IntegerField()),
                ('type', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tigo_money_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('username', models.CharField(max_length=191, unique=True)),
                ('email', models.CharField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=191)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WalletBrands',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=191, unique=True)),
                ('active', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallet_brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('number_account', models.CharField(max_length=191)),
                ('verified', models.IntegerField()),
                ('active', models.IntegerField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wallets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelHasPermissions',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='classifier.permissions')),
                ('model_type', models.CharField(max_length=191)),
                ('model_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'model_has_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelHasRoles',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='classifier.roles')),
                ('model_type', models.CharField(max_length=191)),
                ('model_id', models.PositiveBigIntegerField()),
            ],
            options={
                'db_table': 'model_has_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleHasPermissions',
            fields=[
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='classifier.permissions')),
            ],
            options={
                'db_table': 'role_has_permissions',
                'managed': False,
            },
        ),
    ]
